//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseWebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseWebApplication.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario de aplicación.
        /// </summary>
        public static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una nueva cuenta.
        /// </summary>
        public static string AppUser_CreateTitle {
            get {
                return ResourceManager.GetString("AppUser_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar usuario de aplicacion:.
        /// </summary>
        public static string AppUser_EditTitle {
            get {
                return ResourceManager.GetString("AppUser_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo.
        /// </summary>
        public static string AppUser_Email {
            get {
                return ResourceManager.GetString("AppUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmado.
        /// </summary>
        public static string AppUser_EmailConfirmed {
            get {
                return ResourceManager.GetString("AppUser_EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer nombre.
        /// </summary>
        public static string AppUser_FirstName {
            get {
                return ResourceManager.GetString("AppUser_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de usuarios.
        /// </summary>
        public static string AppUser_IndexTitle {
            get {
                return ResourceManager.GetString("AppUser_IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string AppUser_LastName {
            get {
                return ResourceManager.GetString("AppUser_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido.
        /// </summary>
        public static string AppUser_MiddleLastName {
            get {
                return ResourceManager.GetString("AppUser_MiddleLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo nombre.
        /// </summary>
        public static string AppUser_MiddleName {
            get {
                return ResourceManager.GetString("AppUser_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        public static string AppUser_Password {
            get {
                return ResourceManager.GetString("AppUser_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de usuario.
        /// </summary>
        public static string AppUser_UserName {
            get {
                return ResourceManager.GetString("AppUser_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Fecha.
        /// </summary>
        public static string DummyClass_DateField {
            get {
                return ResourceManager.GetString("DummyClass_DateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de DummyClass.
        /// </summary>
        public static string DummyClass_IndexTitle {
            get {
                return ResourceManager.GetString("DummyClass_IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear nuevo registro.
        /// </summary>
        public static string General_AddNew {
            get {
                return ResourceManager.GetString("General_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor revise su correo electrónico para restablecer su contraseña..
        /// </summary>
        public static string General_CheckYourEmail {
            get {
                return ResourceManager.GetString("General_CheckYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme su correo electrónico.
        /// </summary>
        public static string General_ConfirmYourEmail {
            get {
                return ResourceManager.GetString("General_ConfirmYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string General_Edit {
            get {
                return ResourceManager.GetString("General_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar registro: .
        /// </summary>
        public static string General_EditRow {
            get {
                return ResourceManager.GetString("General_EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string General_EditTitle {
            get {
                return ResourceManager.GetString("General_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string General_EnterYourEmail {
            get {
                return ResourceManager.GetString("General_EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Olvidó su contraseña?.
        /// </summary>
        public static string General_ForgotPassword {
            get {
                return ResourceManager.GetString("General_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmación de contraseña olvidada..
        /// </summary>
        public static string General_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("General_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accede a tu cuenta.
        /// </summary>
        public static string General_GetAccess {
            get {
                return ResourceManager.GetString("General_GetAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string General_GoBack {
            get {
                return ResourceManager.GetString("General_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string General_Home {
            get {
                return ResourceManager.GetString("General_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar sesión.
        /// </summary>
        public static string General_LogIn {
            get {
                return ResourceManager.GetString("General_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme?.
        /// </summary>
        public static string General_RememberMe {
            get {
                return ResourceManager.GetString("General_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restablecer contraseña.
        /// </summary>
        public static string General_ResetPassword {
            get {
                return ResourceManager.GetString("General_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string General_Save {
            get {
                return ResourceManager.GetString("General_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El {0} debe ser al menos de {2} y máximo de {1} caracteres..
        /// </summary>
        public static string General_StringLength_Error {
            get {
                return ResourceManager.GetString("General_StringLength_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione su lenguaje.
        /// </summary>
        public static string Language_SelectLanguage {
            get {
                return ResourceManager.GetString("Language_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
